apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "hpa-{{ include "mychart.name" . }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mychart.name" . }}
  minReplicas: {{ .Values.autoscaler.min_replicas }}
  maxReplicas: {{ .Values.autoscaler.max_replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaler.cpu_average_value }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaler.memory_average_value }}