# # # # # # # # # # # # #   DEV deployment   # # # # # # # # # # # # #
#
# Deploys terraform configuration in `master` branch to DEV environment
# 
# You need to create an Environment named `DEV` with the next secrets:
#   - ARM_BACKEND_NAME: ${{ secrets.ARM_BACKEND_NAME }}
#   - ARM_BACKEND_RG: ${{ secrets.ARM_BACKEND_RG }}
#   - ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#   - ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#   - ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#   - ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
name: AKS Deploy

on:
  workflow_dispatch

env:
  tf_backend_container_name: tfstate
  tf_backend_tfstate_name: workload.tfstate
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Format check
        run: |
          terraform fmt --recursive -check=true                
  apply:
    environment: master
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.x
    - name: Apply
      working-directory: aks_deploy
      run: |
        terraform init -no-color -backend-config=container_name=${{ env.tf_backend_container_name }} -backend-config=key=${{ env.tf_backend_tfstate_name }} \
          -backend-config=storage_account_name=$BACKEND_NAME -backend-config=resource_group_name=$ARM_BACKEND_RG \
          -backend-config=subscription_id=$ARM_SUBSCRIPTION_ID -backend-config=tenant_id=$ARM_TENANT_ID \
          -backend-config=client_id=$ARM_CLIENT_ID -backend-config=client_secret=$ARM_CLIENT_SECRET
        #terraform force-unlock -force 1d5a9877-5b18-7ef5-9b09-5490852efa3c 
        terraform apply -auto-approve -input=false
      env:
        ARM_BACKEND_NAME: ${{ secrets.ARM_BACKEND_NAME }}
        ARM_BACKEND_RG: ${{ secrets.ARM_BACKEND_RG }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}