name: API Build

on:
  workflow_dispatch

env:
  IMAGE_NAME: sdgusecasedag

jobs:
  docker_build:
    name: Push Docker image to Docker Hub
    environment: master    
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_TOKEN }}
      - name: Docker build and push
        working-directory: api_build_docker
        run: |
          docker build --tag="ghcr.io/angelalbertomv/sdg.usecase/sdg_api:v4" -t sdg_api .
          docker push ghcr.io/angelalbertomv/sdg.usecase/sdg_api:v4